#include <furi.h>

/* generated by fbt from .png files in images folder */
#include <mifare_nested_icons.h>

int32_t mifare_nested_app(void* p) {
    UNUSED(p);
    FURI_LOG_I("TEST", "Hello world");
    FURI_LOG_I("TEST", "I'm mifare_nested!");

    return 0;
}
